name: Super-Linter

on:
  push:

jobs:
  super-lint:
    runs-on: ubuntu-latest  # Moved 'runs-on' inside the job definition
    name: Lint code base

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v4.9.5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
